In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

#read the file from local folder
df_train = pd.read_csv("/Users/yanglulu/Desktop/tdi_rentals_dataset.csv")

In [2]:
df_train['rental'].describe()

count     731.000000
mean     4504.348837
std      1937.211452
min        22.000000
25%      3152.000000
50%      4548.000000
75%      5956.000000
max      8714.000000
Name: rental, dtype: float64

In [3]:
#check the info about the dataset to see if there is any Null value or if there is any data type that does not make sense.
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   obs                731 non-null    int64  
 1   date               731 non-null    object 
 2   year               731 non-null    int64  
 3   month              731 non-null    int64  
 4   season             731 non-null    int64  
 5   holiday            731 non-null    int64  
 6   working_day        731 non-null    int64  
 7   weather_condition  731 non-null    int64  
 8   temp               731 non-null    float64
 9   feel_temp          731 non-null    float64
 10  humidity           731 non-null    float64
 11  wind_speed         731 non-null    float64
 12  occasional         731 non-null    int64  
 13  members            731 non-null    int64  
 14  rental             731 non-null    int64  
dtypes: float64(4), int64(10), object(1)
memory usage: 85.8+ KB


In [4]:
df_train.describe()

obs         year       month      season     holiday  \
count  731.000000   731.000000  731.000000  731.000000  731.000000   
mean   366.000000  2011.500684    6.519836    2.496580    0.028728   
std    211.165812     0.500342    3.451913    1.110807    0.167155   
min      1.000000  2011.000000    1.000000    1.000000    0.000000   
25%    183.500000  2011.000000    4.000000    2.000000    0.000000   
50%    366.000000  2012.000000    7.000000    3.000000    0.000000   
75%    548.500000  2012.000000   10.000000    3.000000    0.000000   
max    731.000000  2012.000000   12.000000    4.000000    1.000000   

       working_day  weather_condition        temp   feel_temp    humidity  \
count   731.000000         731.000000  731.000000  731.000000  731.000000   
mean      0.683995           1.395349   20.310776   23.717699    0.627894   
std       0.465233           0.544894    7.505091    8.148059    0.142429   
min       0.000000           1.000000    2.424346    3.953480    0.000000   
25%       0.000000           1.000000   13.820424   16.892125    0.520000   
50%       1.000000           1.000000   20.431653   24.336650    0.626667   
75%       1.000000           2.000000   26.872076   30.430100    0.730209   
max       1.000000           3.000000   35.328347   42.044800    0.972500   

       wind_speed   occasional      members       rental  
count  731.000000   731.000000   731.000000   731.000000  
mean    12.762576   848.176471  3656.172367  4504.348837  
std      5.192357   686.622488  1560.256377  1937.211452  
min      1.500244     2.000000    20.000000    22.000000  
25%      9.041650   315.500000  2497.000000  3152.000000  
50%     12.125325   713.000000  3662.000000  4548.000000  
75%     15.625371  1096.000000  4776.500000  5956.000000  
max     34.000021  3410.000000  6946.000000  8714.000000

In [39]:
y=df_train['rental']
y.head()

0     985
1     801
2    1349
3    1562
4    1600
Name: rental, dtype: int64

In [40]:
X=df_train
X=X.drop(['rental','date'],axis=1)
X.head()

obs  year  month  season  holiday  working_day  weather_condition  \
0    1  2011      1       1        0            0                  2   
1    2  2011      1       1        0            0                  2   
2    3  2011      1       1        0            1                  1   
3    4  2011      1       1        0            1                  1   
4    5  2011      1       1        0            1                  1   

        temp  feel_temp  humidity  wind_speed  occasional  members  
0  14.110847   18.18125  0.805833   10.749882         331      654  
1  14.902598   17.68695  0.696087   16.652113         131      670  
2   8.050924    9.47025  0.437273   16.636703         120     1229  
3   8.200000   10.60610  0.590435   10.739832         108     1454  
4   9.305237   11.46350  0.436957   12.522300          82     1518

In [7]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
import xgboost as xgb

In [8]:
models = []
#models.append(("LR",LogisticRegression()))
#models.append(("NB",GaussianNB()))
models.append(("RF",RandomForestRegressor()))
#models.append(("SVC",SVC()))
models.append(("Dtree",DecisionTreeRegressor()))
#models.append(("XGB",xgb.XGBClassifier()))
#models.append(("KNN",KNeighborsClassifier()))

for name,model in models:
   cv_result = cross_val_score(model,X,y,cv=10)
   print(name, cv_result.mean())

RF 0.971881418142541
Dtree 0.8917007194207391


In [41]:
X=X.drop(['members','occasional'],axis=1)
X.head()

obs  year  month  season  holiday  working_day  weather_condition  \
0    1  2011      1       1        0            0                  2   
1    2  2011      1       1        0            0                  2   
2    3  2011      1       1        0            1                  1   
3    4  2011      1       1        0            1                  1   
4    5  2011      1       1        0            1                  1   

        temp  feel_temp  humidity  wind_speed  
0  14.110847   18.18125  0.805833   10.749882  
1  14.902598   17.68695  0.696087   16.652113  
2   8.050924    9.47025  0.437273   16.636703  
3   8.200000   10.60610  0.590435   10.739832  
4   9.305237   11.46350  0.436957   12.522300

In [10]:
print(X)

     obs  year  month  season  holiday  working_day  weather_condition  \
0      1  2011      1       1        0            0                  2   
1      2  2011      1       1        0            0                  2   
2      3  2011      1       1        0            1                  1   
3      4  2011      1       1        0            1                  1   
4      5  2011      1       1        0            1                  1   
..   ...   ...    ...     ...      ...          ...                ...   
726  727  2012     12       1        0            1                  2   
727  728  2012     12       1        0            1                  2   
728  729  2012     12       1        0            0                  2   
729  730  2012     12       1        0            0                  1   
730  731  2012     12       1        0            1                  2   

          temp  feel_temp  humidity  wind_speed  
0    14.110847   18.18125  0.805833   10.749882  
1    14.902

In [26]:
print(X.values)

[[1.0000000e+00 2.0110000e+03 1.0000000e+00 ... 1.8181250e+01
  8.0583300e-01 1.0749882e+01]
 [2.0000000e+00 2.0110000e+03 1.0000000e+00 ... 1.7686950e+01
  6.9608700e-01 1.6652113e+01]
 [3.0000000e+00 2.0110000e+03 1.0000000e+00 ... 9.4702500e+00
  4.3727300e-01 1.6636703e+01]
 ...
 [7.2900000e+02 2.0120000e+03 1.2000000e+01 ... 1.2120000e+01
  7.5291700e-01 8.3336610e+00]
 [7.3000000e+02 2.0120000e+03 1.2000000e+01 ... 1.1585000e+01
  4.8333300e-01 2.3500518e+01]
 [7.3100000e+02 2.0120000e+03 1.2000000e+01 ... 1.1174350e+01
  5.7750000e-01 1.0374682e+01]]


In [42]:
X=X.values

In [78]:
y=df_train['members']

In [79]:
X=df_train[['temp','obs','year','season','working_day','weather_condition','wind_speed']].values
print(X)

[[1.4110847e+01 1.0000000e+00 2.0110000e+03 ... 0.0000000e+00
  2.0000000e+00 1.0749882e+01]
 [1.4902598e+01 2.0000000e+00 2.0110000e+03 ... 0.0000000e+00
  2.0000000e+00 1.6652113e+01]
 [8.0509240e+00 3.0000000e+00 2.0110000e+03 ... 1.0000000e+00
  1.0000000e+00 1.6636703e+01]
 ...
 [1.0386653e+01 7.2900000e+02 2.0120000e+03 ... 0.0000000e+00
  2.0000000e+00 8.3336610e+00]
 [1.0489153e+01 7.3000000e+02 2.0120000e+03 ... 0.0000000e+00
  1.0000000e+00 2.3500518e+01]
 [8.8491530e+00 7.3100000e+02 2.0120000e+03 ... 1.0000000e+00
  2.0000000e+00 1.0374682e+01]]


In [80]:
models = []
models.append(("LR",LinearRegression()))
#models.append(("LR",LogisticRegression()))
#models.append(("NB",GaussianNB()))
models.append(("RF",RandomForestRegressor()))
#models.append(("SVC",SVC()))
models.append(("Dtree",DecisionTreeRegressor()))
#models.append(("XGB",xgb.XGBClassifier()))
#models.append(("KNN",KNeighborsClassifier()))

for name,model in models:
   cv_result = cross_val_score(model,X,y,cv=20)
   print(name, cv_result.mean())

LR 0.08695149571655539
RF 0.3618111697949229
Dtree -0.21450634415734893


In [81]:
y=df_train['occasional']

In [86]:
X=df_train[['temp','obs','year','working_day','weather_condition']].values
print(X)

[[1.4110847e+01 1.0000000e+00 2.0110000e+03 0.0000000e+00 2.0000000e+00]
 [1.4902598e+01 2.0000000e+00 2.0110000e+03 0.0000000e+00 2.0000000e+00]
 [8.0509240e+00 3.0000000e+00 2.0110000e+03 1.0000000e+00 1.0000000e+00]
 ...
 [1.0386653e+01 7.2900000e+02 2.0120000e+03 0.0000000e+00 2.0000000e+00]
 [1.0489153e+01 7.3000000e+02 2.0120000e+03 0.0000000e+00 1.0000000e+00]
 [8.8491530e+00 7.3100000e+02 2.0120000e+03 1.0000000e+00 2.0000000e+00]]


In [85]:
models = []
models.append(("LR",LinearRegression()))
#models.append(("LR",LogisticRegression()))
#models.append(("NB",GaussianNB()))
models.append(("RF",RandomForestRegressor()))
#models.append(("SVC",SVC()))
models.append(("Dtree",DecisionTreeRegressor()))
#models.append(("XGB",xgb.XGBClassifier()))
#models.append(("KNN",KNeighborsClassifier()))

for name,model in models:
   cv_result = cross_val_score(model,X,y,cv=20)
   print(name, cv_result.mean())

LR -1.3694027680066712
RF 0.08058894853312974
Dtree -1.1551197932824235


In [72]:
X=df_train[['members','occasional']].values
print(X)

[[ 654  331]
 [ 670  131]
 [1229  120]
 ...
 [1182  159]
 [1432  364]
 [2290  439]]


In [73]:
y=df_train['rental']

In [74]:
models = []
models.append(("LR",LinearRegression()))
#models.append(("LR",LogisticRegression()))
#models.append(("NB",GaussianNB()))
models.append(("RF",RandomForestRegressor()))
#models.append(("SVC",SVC()))
models.append(("Dtree",DecisionTreeRegressor()))
#models.append(("XGB",xgb.XGBClassifier()))
#models.append(("KNN",KNeighborsClassifier()))

for name,model in models:
   cv_result = cross_val_score(model,X,y,cv=20)
   print(name, cv_result.mean())

LR 1.0
RF 0.987614026734702
Dtree 0.9662433281477357
